name: redirect-lifecycle-v12
type: typo3
docroot: public
php_version: "8.2"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
performance_mode: none
use_dns_when_possible: true
composer_version: "2"
web_environment:
    - TYPO3_CONTEXT=Development
nodejs_version: "24"
corepack_enable: false
